### ISSUE TITLE
1.13/1.14 Support?

### ISSUE THREAD

**Issue by mrturcot** [Wumpotamus/MinecraftJoypadMod#1]
Hey! Just curious if you plan on adding support for newer versions of MC/forge?

Thanks a lot!

**Comment by ZoeyGlobe** [comment]
I would love this, me and my friend are stuck on older versions until a working controller support mod for the newest versions comes out.

**Comment by Wumpotamus** [comment]
I'm going to go do 1.11, 1.12, and so on first, due to the amount of changes with jumping fast to 1.14, it should take me less time to upgrade to 1.14 with doing that too!

**Comment by mrturcot** [comment]
@Wumpotamus that's awesome to hear! Best of luck on the progress.

**Comment by Wumpotamus** [comment]
This was picked back up by a contributor of the original repo, you guys can go back there, sorry for wasting time
