### ISSUE TITLE
Explore option of switching back to legacy input.

### ISSUE THREAD

**Issue by Wumpotamus** [Wumpotamus/MinecraftJoypadMod#2]
So I was doing some exploring into the JXInput library, the new input library that this mod uses, the library is working on Windows, while I'm on Linux, so I always get defaulted to legacy input. I'd like to explore the possibility of using only the legacy input, so it makes it easier to test and fix issues with the mod, which wouldn't be too easy if someone had an issue with JXInput and I can never figure out why, because I'm on Linux.

**Comment by ChimpD** [comment]
My only concerns with this would be support for the analog triggers on some controllers (ex. Xbox one) and support for sending input to unfocused windows which is necessary for split screen. Otherwise I'm all for making things easier, so if you can resolve those issues then go for it
